application: micromanager-181912
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /rest/tasks
  script: service.tasks.main.APP

- url: /(.+)
  static_files: ./\1
  upload: ./(.*)

- url: /
  static_files: ./index.html
  upload: ./index.html

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
